Add Shiming Zhang to Member
lfapac-open-source-evangelist/education-and-talent-development-sig pull request #11
Opened 2024-03-15 06:09 UTC by wzshiming

2024-03-16 01:54 UTC, sunny0826 requested changes

2024-03-16 01:54 UTC, sunny0826 commented on README.md
> +- [Shiming Zhang](https://github.com/wzshiming) Evangelist Team Member
您好，我在 2024 LFAPAC Evangelists Team  https://evangelists.linuxfoundation.cn/evangelists 中没有找到您的名字，如果您不是 Evangelists Team 成员，请将您的介绍修改为 Education SIG Member

2024-03-18 09:40 UTC, wzshiming commented on README.md
> +- [Shiming Zhang](https://github.com/wzshiming) Evangelist Team Member
已更新

2024-03-18 10:13 UTC, sunny0826 approved these changes
LGTM

2024-03-18 10:13 UTC, merged